producers:
  - name: Genius
    type: genius
    params:
      line: -1
    events:
      idle: ~
      selftest: ~
      alarm: ~

  - name: Input1
    type: generic-input
    params:
      # GPIO line number. (The value -1 simulates input via a file in the file system.)
      line: -1
      # GPIO line bias, can be "default", "pull_up", "pull_down", or "disable".
      bias: "default"
      # GPIO is active low (default: true)
      active_low: true
      # GPIO debounce time (default: 500; unit ms)
      time_debounce: 500
      # Send alarm event when the input is active for longer than this time 
      time_alarm: 5000

    events:
    # This module sends the "alarm" event when the input is active for longer 
    # than the time value and "idle" event when the input becomes inactive afterwards.
      alarm: ~
      idle: ~

# Event names consist of the producer name and the producer's event.
# Example: producer 'generic-input' name: "Input_BMA"
#           event => input_bma_alarm
consumers:
  - name: Tetracontrol
    type: tetracontrol
    params:
      testmode: true
      token: "XYZ"
      url: "http://"
    events:
      genius_alarm:
        enabled: true
        type: callout
        dest: 0000000
        text: "F-RWM Fwh Musterstadt*Hauptstr. 112"
      genius_selftest:
        enabled: true
        type: callout
        dest: 0000000
        text: "Funktionsüberprüfung RWM Fwh Musterstadt"
      genius_idle:
        enabled: true
        type: normal
        dest: 0000000
        text: "Ruhe RWM Fwh Musterstadt"

  - name: Connect
    type: connect
    params:
      token: "ABC"
      testmode: true
      url: "https://connectapi.feuersoftware.com"
    events:
      genius_alarm:
        enabled: true
        ric: "0000000"
        keyword: "F-RWM"
        facts: "Meldereingang"
        source: "Pi Fwh Musterstadt"
        address:
          street: "Hauptstr."
          housenumber: "112"
          zipcode: "112112"
          city: "Musterstadt"

  - name: Ausgabe
    type: generic-output
    params: []
    events:
      input1_alarm:
        enabled: true
      input1_idle:
        enabled: false